name: codecrafters-http-server
version: 0.1.0.0
license: BSD3

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints

dependencies:
  - base >= 4.19 && < 5
  - network # establish a simple TCP network
  - bytestring # useful to send bytes over the network
  - zlib
  - megaparsec >= 9.6.1 && <9.7
  - containers >=0.6.7 && <0.7
  - directory >=1.3 && <1.4
  - mtl >=2.2.2 && <2.4
  - time >=1.9 && <1.15
  - ansi-terminal


executables:
  codecrafters-http-server-exe:
    main: Main.hs
    source-dirs: 
      - app
      - src
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
